Repository e-sensing/sits, pull requests merged in 2021-11, with the labels that each got.

#455 Support `sits_timeline()` to sits model objects
  NAMESPACE
  R/sits_timeline.R
  man/sits_timeline.Rd
Labels: improvement, solved in dev

#467 Full Support to Microsoft Planetary computer
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/sits_accuracy.R
  R/sits_cube.R
  R/sits_gdalcubes.R
  R/sits_raster_api_raster.R
  R/sits_regularize.R
  R/sits_source_api.R
  R/sits_source_api_mspc.R
  R/sits_source_api_stac.R
  R/sits_source_api_usgs.R
  data/cerrado_2classes.rda
  data/samples_modis_4bands.rda
  inst/extdata/config.yml
  inst/extdata/gdalcubes/l8c2l2_usgs.json
  inst/extdata/gdalcubes/landsat_8_c2_l2_mspc.json
  inst/extdata/gdalcubes/ls8_sr_deafrica.json
  inst/extdata/gdalcubes/s2_l2a_deafrica.json
  inst/extdata/gdalcubes/s2la_aws.json
  inst/extdata/gdalcubes/s2la_aws_cogs.json
  inst/extdata/gdalcubes/sentinel_2_l2a_mspc.json
  man/sits_regularize.Rd
  man/source_collection.Rd
  man/source_functions.Rd
  tests/testthat/test-cube.R
  tests/testthat/test-ml.R
  tests/testthat/test-raster.R
  tests/testthat/test-utils.R
Labels: improvement, documentation

#485 Hotfix in `sits_regularize` function
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/sits_config.R
  R/sits_gdalcubes.R
  R/sits_raster_api.R
  R/sits_raster_api_raster.R
  R/sits_raster_api_terra.R
  R/sits_regularize.R
  R/sits_source_api_aws.R
  man/dot-config_gdalcubes_chunk_size.Rd
  man/dot-gc_new_cube.Rd
  man/dot-raster_properties.Rd
  man/sits_regularize.Rd
Labels: bug
