Repository e-sensing/sits, pull requests merged in 2021-09, with the labels that each got.

#356 update README
  README.Rmd
  README.md
  man/figures/README-unnamed-chunk-10-1.png
  man/figures/README-unnamed-chunk-11-1.png
  man/figures/README-unnamed-chunk-6-1.png
  man/figures/README-unnamed-chunk-9-1.png
Labels: documentation

#359 update NEWS
  NEWS.md
Labels: documentation

#361 update docs
  man/dot-sits_plot_classified_image.Rd
  man/plot.classified_image.Rd
Labels: documentation

#364 Hotfix duplicate links
  NEWS.md
  R/sits_source_api_stac.R
Labels: bug

#365 update patch version
  DESCRIPTION
  NEWS.md
Labels: documentation

#372 Update WTSS sits_get_data function
  R/sits_get_data.R
  R/sits_raster_data.R
  inst/extdata/config.yml
  man/dot-sits_get_data_from_wtss.Rd
  man/sits_get_data.Rd
Labels: bug, improvement, documentation

#371 Get spatial resolution from config file in BDC cubes
  R/sits_source_api_bdc.R
  inst/extdata/config.yml
Labels: improvement

#377 Hotfix/bbox
  DESCRIPTION
  NEWS.md
  R/sits_bbox.R
Labels: bug

#381 Dev
  DESCRIPTION
  NEWS.md
  R/sits_bands.R
  R/sits_bands_set.R
  R/sits_bbox.R
  R/sits_config.R
  R/sits_select.R
  R/sits_som.R
Labels: improvement

#386 add `.source_bands_resampling()` function
  R/sits_source_api.R
Labels: improvement

#389 Feature new function `sits_list_collections()`
  NAMESPACE
  R/sits_config.R
  man/sits_configuration.Rd
  man/sits_view.Rd
  man/source_bands.Rd
Labels: improvement

#391 Pre release 0.14.1
  DESCRIPTION
  NEWS.md
Labels: release

#394 closes #393
  DESCRIPTION
  NEWS.md
  R/sits_gdalcubes.R
Labels: bug
