Repository e-sensing/sits, pull requests merged in 2022-08, with the labels that each got.

#825 :lady_beetle: Hotfix to `sits_apply` bug
  DESCRIPTION
  R/sits_apply.R
  R/sits_classification.R
  R/sits_cube.R
  R/sits_cube_aux_functions.R
  R/sits_get_data.R
  R/sits_raster_sub_image.R
  R/sits_source_api_mpc.R
  R/sits_source_api_usgs.R
  inst/extdata/config.yml
  man/dot-cube_filter.Rd
  man/dot-sits_raster_sub_image_from_block.Rd
  man/sits_cube.Rd
  man/sits_tuning.Rd
  tests/testthat/test-cube.R
Labels: bug

#817 Remove duplicated points in and warning message in `sits_get_data()`
  R/sits_get_data.R
  R/sits_space_time_operations.R
Labels: bug, improvement

#832 Hotfix `sits_regularize` bug
  DESCRIPTION
  NAMESPACE
  R/sits_apply.R
  R/sits_cube_aux_functions.R
  R/sits_gdalcubes.R
  R/sits_get_data.R
  README.md
  inst/extdata/config_internals.yml
  man/dot-cube_is_token_expires.Rd
  man/dot-sits_get_ts.Rd
  man/figures/README-unnamed-chunk-10-1.png
  man/figures/README-unnamed-chunk-11-1.png
  man/figures/README-unnamed-chunk-13-1.png
  man/figures/README-unnamed-chunk-14-1.png
  man/figures/README-unnamed-chunk-15-1.png
  man/figures/README-unnamed-chunk-9-1.png
Labels: bug

#835 Merge with master branch
  NAMESPACE
  R/sits_apply.R
  R/sits_classification.R
  R/sits_cube.R
  R/sits_cube_aux_functions.R
  R/sits_gdalcubes.R
  R/sits_get_data.R
  R/sits_plot.R
  R/sits_raster_sub_image.R
  R/sits_source_api_mpc.R
  R/sits_source_api_usgs.R
  README.Rmd
  README.md
  inst/extdata/config.yml
  inst/extdata/config_internals.yml
  man/dot-cube_filter.Rd
  man/dot-cube_is_token_expires.Rd
  man/dot-sits_raster_sub_image_from_block.Rd
  man/figures/README-unnamed-chunk-10-1.png
  man/figures/README-unnamed-chunk-11-1.png
  man/figures/README-unnamed-chunk-13-1.png
  man/figures/README-unnamed-chunk-14-1.png
  man/figures/README-unnamed-chunk-15-1.png
  man/figures/README-unnamed-chunk-9-1.png
  man/sits_cube.Rd
  tests/testthat/test-cube.R
Labels: documentation

#838 Fix `sits_get_data` bug
  DESCRIPTION
  R/sits_sf.R
  README.md
Labels: bug

#843 add issue template
  .Rbuildignore
  .github/.gitignore
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/improvement_request.md
  .github/ISSUE_TEMPLATE/new_api_function.md
  .github/ISSUE_TEMPLATE/other_issue.md
Labels: documentation

#845 Fix resume feature for BDC cubes
  DESCRIPTION
  R/sits_classify_cube.R
  R/sits_cube_aux_functions.R
  R/sits_label_classification.R
  R/sits_smooth.R
  README.md
  man/dot-cube_is_equal_bbox.Rd
  tests/testthat/test-raster.R
Labels: bug

#851 Hotfix/local cube bdc
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/RcppExports.R
  R/sits_apply.R
  R/sits_bbox.R
  R/sits_gdalcubes.R
  R/sits_label_classification.R
  R/sits_labels.R
  R/sits_raster_api_terra.R
  R/sits_raster_data.R
  R/sits_smooth.R
  R/sits_smooth_aux_functions.R
  inst/extdata/config.yml
  man/dot-gc_detect_crs_type.Rd
  man/dot-label_estimate_block_size.Rd
  man/dot-sits_image_classified_get_ts.Rd
  man/tick-sits_labels-set-tick.Rd
  src/RcppExports.cpp
  src/label_class.cpp
Labels: bug
