Repository e-sensing/sits, pull requests merged in 2024-11, with the labels that each got.

#1239 replace probability fractions with NA in classification results
  R/api_classify.R
  R/api_download.R
  src/smooth_bayes.cpp
  tests/testthat/test-classification.R
  tests/testthat/test-cube_copy.R
Labels: improvement

#1241 add exclusion mask for sits_smooth
  R/api_smooth.R
  R/sits_smooth.R
  man/sits_smooth.Rd
Labels: new API function

#1243 Fix segmentation error
  R/api_raster_terra.R
  R/api_tmap_v4.R
  man/sits_cube_copy.Rd
  man/sits_merge.Rd
Labels: bug
