Repository e-sensing/sits, pull requests merged in 2024-07, with the labels that each got.

#1166 Adjust base cube classification to extract time series using block strategy
  NAMESPACE
  R/api_check.R
  R/api_classify.R
  R/api_cube.R
  R/api_data.R
  R/api_plot_time_series.R
  R/api_plot_vector.R
  R/api_predictors.R
  R/api_samples.R
  R/api_tile.R
  R/sits_add_base_cube.R
  R/sits_bands.R
  R/sits_classify.R
  R/sits_get_data.R
  man/sits_bands.Rd
Labels: improvement

#1170 sources: DEAustralia and World Cover support
  DESCRIPTION
  NAMESPACE
  R/api_check.R
  R/api_conf.R
  R/api_cube.R
  R/api_data.R
  R/api_plot_raster.R
  R/api_raster_sub_image.R
  R/api_samples.R
  R/api_source.R
  R/api_source_deaustralia.R
  R/api_source_local.R
  R/api_source_stac.R
  R/api_source_terrascope.R
  R/api_tile.R
  R/api_ts.R
  R/api_view.R
  R/sits_add_base_cube.R
  R/sits_cube.R
  R/sits_get_data.R
  R/sits_sample_functions.R
  R/sits_segmentation.R
  inst/extdata/config_messages.yml
  inst/extdata/sources/config_source_deaustralia.yml
  inst/extdata/sources/config_source_terrascope.yml
  man/sits_cube.Rd
  man/sits_get_data.Rd
  tests/testthat/test-cube-deaustralia.R
  tests/testthat/test-cube-terrascope.R
  tests/testthat/test-data.R
  tests/testthat/test-labels.R
  tests/testthat/test-mosaic.R
  tests/testthat/test-plot.R
  tests/testthat/test-raster.R
  tests/testthat/test-reclassify.R
  tests/testthat/test-samples.R
  tests/testthat/test-view.R
Labels: improvement, new API function

#1171 fix mpc stac error
  R/api_stac.R
Labels: bug

#1172 update grd class definition strategy
  R/api_cube.R
Labels: bug

#1173 handle missing points from base cube
  R/api_data.R
Labels: bug

#1174 fix segmentation for base_raster_cube
  R/api_segments.R
  tests/testthat/test-segmentation.R
Labels: bug

#1176 Convert from `httr` package to `httr2` package
  DESCRIPTION
  NAMESPACE
  R/api_conf.R
  R/api_cube.R
  R/api_download.R
  R/api_opensearch.R
  R/api_request.R
  R/api_request_httr2.R
  R/api_source_mpc.R
  R/api_utils.R
  inst/extdata/config_internals.yml
  tests/testthat/test-request.R
Labels: improvement

#1177 fix returned class from sits_get_data with base_cube
  R/api_data.R
  R/api_request_httr2.R
  tests/testthat/test-data.R
Labels: bug

#1178 fix sf object creation in the s2-tile handling
  R/api_s2tile.R
Labels: bug

#1179 Fix request bug in `.cube_token_generator` and update `rstac` version in DESCRIPTION
  DESCRIPTION
  R/api_cube.R
  R/api_download.R
  R/api_request.R
  R/api_request_httr2.R
  R/api_utils.R
Labels: bug, improvement

#1181 fix segments classification with base cube
  R/api_classify.R
  R/api_segments.R
  R/api_tile.R
  R/sits_classify.R
Labels: bug

#1185 fix tuning operation with torch models
  R/api_torch.R
  R/sits_classify.R
  R/sits_lighttae.R
  R/sits_mlp.R
  R/sits_tae.R
  R/sits_tempcnn.R
  R/sits_tuning.R
  man/sits_classify.Rd
  man/sits_tuning.Rd
Labels: bug
