Repository e-sensing/sits, pull requests merged in 2025-02, with the labels that each got.

#1282 Refactoring `sits_merge` function and tests
  NAMESPACE
  R/api_check.R
  R/api_conf.R
  R/api_cube.R
  R/api_merge.R
  R/api_regularize.R
  R/api_source_sdc.R
  R/api_tile.R
  R/sits_merge.R
  R/sits_regularize.R
  inst/extdata/config_messages.yml
  inst/extdata/sources/config_source_deafrica.yml
  inst/extdata/sources/config_source_mpc.yml
  inst/extdata/sources/config_source_planet.yaml
  inst/extdata/sources/config_source_sdc.yml
  inst/extdata/sources/config_source_terrascope.yml
  tests/testthat/test-merge.R
Labels: improvement

#1286 Update sits_cube_copy function
  R/api_cube.R
  R/sits_cube_copy.R
Labels: documentation

#1287 fix docs and raster api call
  R/api_detect_change.R
  R/api_raster.R
Labels: improvement

#1293 Fix vector cube classification with local cubes
  DESCRIPTION
  R/api_chunks.R
  R/api_classify.R
  R/api_segments.R
Labels: bug

#1297 enable openmp in cpp code
  src/Makevars
Labels: bug
