Repository e-sensing/sits, pull requests merged in 2025-07, with the labels that each got.

#1351 Fix multicores bug when using `.crop()` function and add `labels` in `sits_select()`
  NAMESPACE
  R/api_check.R
  R/api_crop.R
  R/api_data.R
  R/api_samples.R
  R/api_select.R
  R/api_ts.R
  R/sits_cluster.R
  R/sits_dtw.R
  R/sits_reduce.R
  R/sits_select.R
  inst/extdata/config_messages.yml
  inst/extdata/sources/config_source_usgs.yml
  man/sits_reduce.Rd
  man/sits_select.Rd
  tests/testthat/test-select.R
Labels: bug, improvement

#1352 Fix `sits_clean()` multicores bug and `sits_reclassify()` block size
  R/api_classify.R
  R/api_clean.R
  R/api_raster.R
  R/api_source_local.R
  R/sits_classify.R
  R/sits_clean.R
  R/sits_cube_local.R
  R/sits_get_data.R
  R/sits_reclassify.R
  inst/extdata/config_messages.yml
  man/sits_classify.raster_cube.Rd
  man/sits_cube.results_cube.Rd
  src/kernel.cpp
Labels: bug

#1353 enhance `summary()` with multicores / chunked implementation
  NAMESPACE
  R/api_check.R
  R/api_uncertainty.R
  R/sits_classify.R
  R/sits_cube_copy.R
  R/sits_imputation.R
  R/sits_summary.R
  inst/extdata/config_messages.yml
  man/sits_impute.Rd
  man/summary.variance_cube.Rd
  tests/testthat/test-data.R
  tests/testthat/test-uncertainty.R
Labels: improvement

#1358 fix crop in sits_classify, enhance sits_regularize for rtc and fix mosaic band config
  NAMESPACE
  R/api_crop.R
  R/api_mosaic.R
  R/api_regularize.R
  R/sits_grid_systems.R
  inst/extdata/config_messages.yml
Labels: improvement

#1359 Enhance stratified sampling performance and fix classification blocks calculation
  R/RcppExports.R
  R/api_block.R
  R/api_raster.R
  R/api_samples.R
  R/sits_classify.R
  R/sits_config.R
  R/sits_sample_functions.R
  inst/extdata/config_messages.yml
  man/sits_config_user_file.Rd
  man/sits_stratified_sampling.Rd
  src/RcppExports.cpp
  src/sampling.cpp
  tests/testthat/test-samples.R
Labels: improvement

#1360 fix check_samples export
  NAMESPACE
  R/api_check.R
Labels: bug

#1365 enhance blocks usage in sits_reclassify
  R/api_reclassify.R
  R/sits_reclassify.R
Labels: improvement
